//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kf2server_tbot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Prompts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prompts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kf2server_tbot.Prompts", typeof(Prompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added/Updated user {0} with specified roles.
        /// </summary>
        internal static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast: &quot;{0}&quot;.
        /// </summary>
        internal static string AdminSay {
            get {
                return ResourceManager.GetString("AdminSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing game type to {0}.
        /// </summary>
        internal static string ChangeGameType {
            get {
                return ResourceManager.GetString("ChangeGameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing game type to {0} and map to {1}.
        /// </summary>
        internal static string ChangeGameTypeAndMap {
            get {
                return ResourceManager.GetString("ChangeGameTypeAndMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing map to {0}.
        /// </summary>
        internal static string ChangeMap {
            get {
                return ResourceManager.GetString("ChangeMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing game difficulty to {0}.
        /// </summary>
        internal static string GameDifficulty {
            get {
                return ResourceManager.GetString("GameDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing game difficulty to {0} and length to {1}.
        /// </summary>
        internal static string GameDifficultyAndLength {
            get {
                return ResourceManager.GetString("GameDifficultyAndLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing game length to {0}.
        /// </summary>
        internal static string GameLength {
            get {
                return ResourceManager.GetString("GameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game password has been removed.
        /// </summary>
        internal static string GamePasswordOff {
            get {
                return ResourceManager.GetString("GamePasswordOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game password has been set {0}.
        /// </summary>
        internal static string GamePasswordOn {
            get {
                return ResourceManager.GetString("GamePasswordOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kicking {0} from current game.
        /// </summary>
        internal static string Kick {
            get {
                return ResourceManager.GetString("Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently online: \n{0}.
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed roles and/or user {0}.
        /// </summary>
        internal static string RemoveUser {
            get {
                return ResourceManager.GetString("RemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatID is: {0}\n Set this value in the config server-sided, and restart.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently offline, or not responding to requests.
        /// </summary>
        internal static string StatusFailure {
            get {
                return ResourceManager.GetString("StatusFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Game Session: \n{0}.
        /// </summary>
        internal static string StatusSuccess {
            get {
                return ResourceManager.GetString("StatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $TBOTCLIENT.
        /// </summary>
        internal static string TBotClientName {
            get {
                return ResourceManager.GetString("TBotClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $TBOTSERVER.
        /// </summary>
        internal static string TBotServerName {
            get {
                return ResourceManager.GetString("TBotServerName", resourceCulture);
            }
        }
    }
}
