//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tbot_client.KF2ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseValue", Namespace="http://schemas.datacontract.org/2004/07/kf2server_tbot_client.Utils")]
    [System.SerializableAttribute()]
    public partial class ResponseValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KF2ServiceReference.IKF2Service")]
    public interface IKF2Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/Status", ReplyAction="http://tempuri.org/IKF2Service/StatusResponse")]
        tbot_client.KF2ServiceReference.ResponseValue Status();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/Status", ReplyAction="http://tempuri.org/IKF2Service/StatusResponse")]
        System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> StatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/ChangeGameType", ReplyAction="http://tempuri.org/IKF2Service/ChangeGameTypeResponse")]
        tbot_client.KF2ServiceReference.ResponseValue ChangeGameType(string gametype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/ChangeGameType", ReplyAction="http://tempuri.org/IKF2Service/ChangeGameTypeResponse")]
        System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> ChangeGameTypeAsync(string gametype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/ChangeMap", ReplyAction="http://tempuri.org/IKF2Service/ChangeMapResponse")]
        tbot_client.KF2ServiceReference.ResponseValue ChangeMap(string map);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/ChangeMap", ReplyAction="http://tempuri.org/IKF2Service/ChangeMapResponse")]
        System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> ChangeMapAsync(string map);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/ChangeGametypeAndMap", ReplyAction="http://tempuri.org/IKF2Service/ChangeGametypeAndMapResponse")]
        tbot_client.KF2ServiceReference.ResponseValue ChangeGametypeAndMap(string gametype, string map);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/ChangeGametypeAndMap", ReplyAction="http://tempuri.org/IKF2Service/ChangeGametypeAndMapResponse")]
        System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> ChangeGametypeAndMapAsync(string gametype, string map);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/Online", ReplyAction="http://tempuri.org/IKF2Service/OnlineResponse")]
        tbot_client.KF2ServiceReference.ResponseValue Online();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/Online", ReplyAction="http://tempuri.org/IKF2Service/OnlineResponse")]
        System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> OnlineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/Kick", ReplyAction="http://tempuri.org/IKF2Service/KickResponse")]
        tbot_client.KF2ServiceReference.ResponseValue Kick(string playername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/Kick", ReplyAction="http://tempuri.org/IKF2Service/KickResponse")]
        System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> KickAsync(string playername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/GamePasswordOn", ReplyAction="http://tempuri.org/IKF2Service/GamePasswordOnResponse")]
        tbot_client.KF2ServiceReference.ResponseValue GamePasswordOn(string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/GamePasswordOn", ReplyAction="http://tempuri.org/IKF2Service/GamePasswordOnResponse")]
        System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> GamePasswordOnAsync(string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/GamePasswordOff", ReplyAction="http://tempuri.org/IKF2Service/GamePasswordOffResponse")]
        tbot_client.KF2ServiceReference.ResponseValue GamePasswordOff();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/GamePasswordOff", ReplyAction="http://tempuri.org/IKF2Service/GamePasswordOffResponse")]
        System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> GamePasswordOffAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/GameDifficulty", ReplyAction="http://tempuri.org/IKF2Service/GameDifficultyResponse")]
        tbot_client.KF2ServiceReference.ResponseValue GameDifficulty(string difficulty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/GameDifficulty", ReplyAction="http://tempuri.org/IKF2Service/GameDifficultyResponse")]
        System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> GameDifficultyAsync(string difficulty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/GameLength", ReplyAction="http://tempuri.org/IKF2Service/GameLengthResponse")]
        tbot_client.KF2ServiceReference.ResponseValue GameLength(string length);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/GameLength", ReplyAction="http://tempuri.org/IKF2Service/GameLengthResponse")]
        System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> GameLengthAsync(string length);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/GameDifficultyAndLength", ReplyAction="http://tempuri.org/IKF2Service/GameDifficultyAndLengthResponse")]
        tbot_client.KF2ServiceReference.ResponseValue GameDifficultyAndLength(string difficulty, string length);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/GameDifficultyAndLength", ReplyAction="http://tempuri.org/IKF2Service/GameDifficultyAndLengthResponse")]
        System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> GameDifficultyAndLengthAsync(string difficulty, string length);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/AdminSay", ReplyAction="http://tempuri.org/IKF2Service/AdminSayResponse")]
        tbot_client.KF2ServiceReference.ResponseValue AdminSay(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/AdminSay", ReplyAction="http://tempuri.org/IKF2Service/AdminSayResponse")]
        System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> AdminSayAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/Pause", ReplyAction="http://tempuri.org/IKF2Service/PauseResponse")]
        tbot_client.KF2ServiceReference.ResponseValue Pause();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/Pause", ReplyAction="http://tempuri.org/IKF2Service/PauseResponse")]
        System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> PauseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/AddUser", ReplyAction="http://tempuri.org/IKF2Service/AddUserResponse")]
        tbot_client.KF2ServiceReference.ResponseValue AddUser(string telegramUUID, string[] roles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/AddUser", ReplyAction="http://tempuri.org/IKF2Service/AddUserResponse")]
        System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> AddUserAsync(string telegramUUID, string[] roles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/RemoveUser", ReplyAction="http://tempuri.org/IKF2Service/RemoveUserResponse")]
        tbot_client.KF2ServiceReference.ResponseValue RemoveUser(string telegramUUID, string[] roles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/RemoveUser", ReplyAction="http://tempuri.org/IKF2Service/RemoveUserResponse")]
        System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> RemoveUserAsync(string telegramUUID, string[] roles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/Test", ReplyAction="http://tempuri.org/IKF2Service/TestResponse")]
        tbot_client.KF2ServiceReference.ResponseValue Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/Test", ReplyAction="http://tempuri.org/IKF2Service/TestResponse")]
        System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> TestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/Setup", ReplyAction="http://tempuri.org/IKF2Service/SetupResponse")]
        tbot_client.KF2ServiceReference.ResponseValue Setup(string chatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKF2Service/Setup", ReplyAction="http://tempuri.org/IKF2Service/SetupResponse")]
        System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> SetupAsync(string telegramUUID, string chatId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKF2ServiceChannel : tbot_client.KF2ServiceReference.IKF2Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KF2ServiceClient : System.ServiceModel.ClientBase<tbot_client.KF2ServiceReference.IKF2Service>, tbot_client.KF2ServiceReference.IKF2Service {
        
        public KF2ServiceClient() {
        }
        
        public KF2ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KF2ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KF2ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KF2ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public tbot_client.KF2ServiceReference.ResponseValue Status() {
            return base.Channel.Status();
        }
        
        public System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> StatusAsync() {
            return base.Channel.StatusAsync();
        }
        
        public tbot_client.KF2ServiceReference.ResponseValue ChangeGameType(string gametype) {
            return base.Channel.ChangeGameType(gametype);
        }
        
        public System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> ChangeGameTypeAsync(string gametype) {
            return base.Channel.ChangeGameTypeAsync(gametype);
        }
        
        public tbot_client.KF2ServiceReference.ResponseValue ChangeMap(string map) {
            return base.Channel.ChangeMap(map);
        }
        
        public System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> ChangeMapAsync(string map) {
            return base.Channel.ChangeMapAsync(map);
        }
        
        public tbot_client.KF2ServiceReference.ResponseValue ChangeGametypeAndMap(string gametype, string map) {
            return base.Channel.ChangeGametypeAndMap(gametype, map);
        }
        
        public System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> ChangeGametypeAndMapAsync(string gametype, string map) {
            return base.Channel.ChangeGametypeAndMapAsync(gametype, map);
        }
        
        public tbot_client.KF2ServiceReference.ResponseValue Online() {
            return base.Channel.Online();
        }
        
        public System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> OnlineAsync() {
            return base.Channel.OnlineAsync();
        }
        
        public tbot_client.KF2ServiceReference.ResponseValue Kick(string playername) {
            return base.Channel.Kick(playername);
        }
        
        public System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> KickAsync(string playername) {
            return base.Channel.KickAsync(playername);
        }
        
        public tbot_client.KF2ServiceReference.ResponseValue GamePasswordOn(string pwd) {
            return base.Channel.GamePasswordOn(pwd);
        }
        
        public System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> GamePasswordOnAsync(string pwd) {
            return base.Channel.GamePasswordOnAsync(pwd);
        }
        
        public tbot_client.KF2ServiceReference.ResponseValue GamePasswordOff() {
            return base.Channel.GamePasswordOff();
        }
        
        public System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> GamePasswordOffAsync() {
            return base.Channel.GamePasswordOffAsync();
        }
        
        public tbot_client.KF2ServiceReference.ResponseValue GameDifficulty(string difficulty) {
            return base.Channel.GameDifficulty(difficulty);
        }
        
        public System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> GameDifficultyAsync(string difficulty) {
            return base.Channel.GameDifficultyAsync(difficulty);
        }
        
        public tbot_client.KF2ServiceReference.ResponseValue GameLength(string length) {
            return base.Channel.GameLength(length);
        }
        
        public System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> GameLengthAsync(string length) {
            return base.Channel.GameLengthAsync(length);
        }
        
        public tbot_client.KF2ServiceReference.ResponseValue GameDifficultyAndLength(string difficulty, string length) {
            return base.Channel.GameDifficultyAndLength(difficulty, length);
        }
        
        public System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> GameDifficultyAndLengthAsync(string difficulty, string length) {
            return base.Channel.GameDifficultyAndLengthAsync(difficulty, length);
        }
        
        public tbot_client.KF2ServiceReference.ResponseValue AdminSay(string message) {
            return base.Channel.AdminSay(message);
        }
        
        public System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> AdminSayAsync(string message) {
            return base.Channel.AdminSayAsync(message);
        }
        
        public tbot_client.KF2ServiceReference.ResponseValue Pause() {
            return base.Channel.Pause();
        }
        
        public System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> PauseAsync() {
            return base.Channel.PauseAsync();
        }
        
        public tbot_client.KF2ServiceReference.ResponseValue AddUser(string telegramUUID, string[] roles) {
            return base.Channel.AddUser(telegramUUID, roles);
        }
        
        public System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> AddUserAsync(string telegramUUID, string[] roles) {
            return base.Channel.AddUserAsync(telegramUUID, roles);
        }
        
        public tbot_client.KF2ServiceReference.ResponseValue RemoveUser(string telegramUUID, string[] roles) {
            return base.Channel.RemoveUser(telegramUUID, roles);
        }
        
        public System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> RemoveUserAsync(string telegramUUID, string[] roles) {
            return base.Channel.RemoveUserAsync(telegramUUID, roles);
        }
        
        public tbot_client.KF2ServiceReference.ResponseValue Test() {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> TestAsync() {
            return base.Channel.TestAsync();
        }
        
        public tbot_client.KF2ServiceReference.ResponseValue Setup(string chatId) {
            return base.Channel.Setup(chatId);
        }
        
        public System.Threading.Tasks.Task<tbot_client.KF2ServiceReference.ResponseValue> SetupAsync(string telegramUUID, string chatId) {
            return base.Channel.SetupAsync(telegramUUID, chatId);
        }
    }
}
