//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tbot_client.Settings {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseValue", Namespace="http://schemas.datacontract.org/2004/07/kf2server_tbot_client.Utils")]
    [System.SerializableAttribute()]
    public partial class ResponseValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Settings.ISettingsService")]
    public interface ISettingsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISettingsService/General_Game_GameDifficulty", ReplyAction="http://tempuri.org/ISettingsService/General_Game_GameDifficultyResponse")]
        tbot_client.Settings.ResponseValue General_Game_GameDifficulty(string difficulty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISettingsService/General_Game_GameDifficulty", ReplyAction="http://tempuri.org/ISettingsService/General_Game_GameDifficultyResponse")]
        System.Threading.Tasks.Task<tbot_client.Settings.ResponseValue> General_Game_GameDifficultyAsync(string difficulty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISettingsService/General_Game_GameLength", ReplyAction="http://tempuri.org/ISettingsService/General_Game_GameLengthResponse")]
        tbot_client.Settings.ResponseValue General_Game_GameLength(string length);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISettingsService/General_Game_GameLength", ReplyAction="http://tempuri.org/ISettingsService/General_Game_GameLengthResponse")]
        System.Threading.Tasks.Task<tbot_client.Settings.ResponseValue> General_Game_GameLengthAsync(string length);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISettingsService/General_Game_GameDifficultyAndLength", ReplyAction="http://tempuri.org/ISettingsService/General_Game_GameDifficultyAndLengthResponse")]
        tbot_client.Settings.ResponseValue General_Game_GameDifficultyAndLength(string difficulty, string length);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISettingsService/General_Game_GameDifficultyAndLength", ReplyAction="http://tempuri.org/ISettingsService/General_Game_GameDifficultyAndLengthResponse")]
        System.Threading.Tasks.Task<tbot_client.Settings.ResponseValue> General_Game_GameDifficultyAndLengthAsync(string difficulty, string length);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISettingsServiceChannel : tbot_client.Settings.ISettingsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SettingsServiceClient : System.ServiceModel.ClientBase<tbot_client.Settings.ISettingsService>, tbot_client.Settings.ISettingsService {
        
        public SettingsServiceClient() {
        }
        
        public SettingsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SettingsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SettingsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SettingsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public tbot_client.Settings.ResponseValue General_Game_GameDifficulty(string difficulty) {
            return base.Channel.General_Game_GameDifficulty(difficulty);
        }
        
        public System.Threading.Tasks.Task<tbot_client.Settings.ResponseValue> General_Game_GameDifficultyAsync(string difficulty) {
            return base.Channel.General_Game_GameDifficultyAsync(difficulty);
        }
        
        public tbot_client.Settings.ResponseValue General_Game_GameLength(string length) {
            return base.Channel.General_Game_GameLength(length);
        }
        
        public System.Threading.Tasks.Task<tbot_client.Settings.ResponseValue> General_Game_GameLengthAsync(string length) {
            return base.Channel.General_Game_GameLengthAsync(length);
        }
        
        public tbot_client.Settings.ResponseValue General_Game_GameDifficultyAndLength(string difficulty, string length) {
            return base.Channel.General_Game_GameDifficultyAndLength(difficulty, length);
        }
        
        public System.Threading.Tasks.Task<tbot_client.Settings.ResponseValue> General_Game_GameDifficultyAndLengthAsync(string difficulty, string length) {
            return base.Channel.General_Game_GameDifficultyAndLengthAsync(difficulty, length);
        }
    }
}
