//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tbot_client.CurrentGame {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseValue", Namespace="http://schemas.datacontract.org/2004/07/kf2server_tbot_client.Utils")]
    [System.SerializableAttribute()]
    public partial class ResponseValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurrentGame.ICurrentGameService")]
    public interface ICurrentGameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrentGameService/Status", ReplyAction="http://tempuri.org/ICurrentGameService/StatusResponse")]
        tbot_client.CurrentGame.ResponseValue Status();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrentGameService/Status", ReplyAction="http://tempuri.org/ICurrentGameService/StatusResponse")]
        System.Threading.Tasks.Task<tbot_client.CurrentGame.ResponseValue> StatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrentGameService/ChangeGameType", ReplyAction="http://tempuri.org/ICurrentGameService/ChangeGameTypeResponse")]
        tbot_client.CurrentGame.ResponseValue ChangeGameType(string gametype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrentGameService/ChangeGameType", ReplyAction="http://tempuri.org/ICurrentGameService/ChangeGameTypeResponse")]
        System.Threading.Tasks.Task<tbot_client.CurrentGame.ResponseValue> ChangeGameTypeAsync(string gametype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrentGameService/ChangeMap", ReplyAction="http://tempuri.org/ICurrentGameService/ChangeMapResponse")]
        tbot_client.CurrentGame.ResponseValue ChangeMap(string map);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrentGameService/ChangeMap", ReplyAction="http://tempuri.org/ICurrentGameService/ChangeMapResponse")]
        System.Threading.Tasks.Task<tbot_client.CurrentGame.ResponseValue> ChangeMapAsync(string map);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrentGameService/ChangeGametypeAndMap", ReplyAction="http://tempuri.org/ICurrentGameService/ChangeGametypeAndMapResponse")]
        tbot_client.CurrentGame.ResponseValue ChangeGametypeAndMap(string gametype, string map);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrentGameService/ChangeGametypeAndMap", ReplyAction="http://tempuri.org/ICurrentGameService/ChangeGametypeAndMapResponse")]
        System.Threading.Tasks.Task<tbot_client.CurrentGame.ResponseValue> ChangeGametypeAndMapAsync(string gametype, string map);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrentGameService/Online", ReplyAction="http://tempuri.org/ICurrentGameService/OnlineResponse")]
        tbot_client.CurrentGame.ResponseValue Online();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrentGameService/Online", ReplyAction="http://tempuri.org/ICurrentGameService/OnlineResponse")]
        System.Threading.Tasks.Task<tbot_client.CurrentGame.ResponseValue> OnlineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrentGameService/Kick", ReplyAction="http://tempuri.org/ICurrentGameService/KickResponse")]
        tbot_client.CurrentGame.ResponseValue Kick(string playername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrentGameService/Kick", ReplyAction="http://tempuri.org/ICurrentGameService/KickResponse")]
        System.Threading.Tasks.Task<tbot_client.CurrentGame.ResponseValue> KickAsync(string playername);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICurrentGameServiceChannel : tbot_client.CurrentGame.ICurrentGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrentGameServiceClient : System.ServiceModel.ClientBase<tbot_client.CurrentGame.ICurrentGameService>, tbot_client.CurrentGame.ICurrentGameService {
        
        public CurrentGameServiceClient() {
        }
        
        public CurrentGameServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrentGameServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrentGameServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrentGameServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public tbot_client.CurrentGame.ResponseValue Status() {
            return base.Channel.Status();
        }
        
        public System.Threading.Tasks.Task<tbot_client.CurrentGame.ResponseValue> StatusAsync() {
            return base.Channel.StatusAsync();
        }
        
        public tbot_client.CurrentGame.ResponseValue ChangeGameType(string gametype) {
            return base.Channel.ChangeGameType(gametype);
        }
        
        public System.Threading.Tasks.Task<tbot_client.CurrentGame.ResponseValue> ChangeGameTypeAsync(string gametype) {
            return base.Channel.ChangeGameTypeAsync(gametype);
        }
        
        public tbot_client.CurrentGame.ResponseValue ChangeMap(string map) {
            return base.Channel.ChangeMap(map);
        }
        
        public System.Threading.Tasks.Task<tbot_client.CurrentGame.ResponseValue> ChangeMapAsync(string map) {
            return base.Channel.ChangeMapAsync(map);
        }
        
        public tbot_client.CurrentGame.ResponseValue ChangeGametypeAndMap(string gametype, string map) {
            return base.Channel.ChangeGametypeAndMap(gametype, map);
        }
        
        public System.Threading.Tasks.Task<tbot_client.CurrentGame.ResponseValue> ChangeGametypeAndMapAsync(string gametype, string map) {
            return base.Channel.ChangeGametypeAndMapAsync(gametype, map);
        }
        
        public tbot_client.CurrentGame.ResponseValue Online() {
            return base.Channel.Online();
        }
        
        public System.Threading.Tasks.Task<tbot_client.CurrentGame.ResponseValue> OnlineAsync() {
            return base.Channel.OnlineAsync();
        }
        
        public tbot_client.CurrentGame.ResponseValue Kick(string playername) {
            return base.Channel.Kick(playername);
        }
        
        public System.Threading.Tasks.Task<tbot_client.CurrentGame.ResponseValue> KickAsync(string playername) {
            return base.Channel.KickAsync(playername);
        }
    }
}
