//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tbot_client.Miscellaneous {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseValue", Namespace="http://schemas.datacontract.org/2004/07/kf2server_tbot_client.Utils")]
    [System.SerializableAttribute()]
    public partial class ResponseValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Miscellaneous.IMiscellaneousService")]
    public interface IMiscellaneousService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscellaneousService/AdminSay", ReplyAction="http://tempuri.org/IMiscellaneousService/AdminSayResponse")]
        tbot_client.Miscellaneous.ResponseValue AdminSay(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscellaneousService/AdminSay", ReplyAction="http://tempuri.org/IMiscellaneousService/AdminSayResponse")]
        System.Threading.Tasks.Task<tbot_client.Miscellaneous.ResponseValue> AdminSayAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscellaneousService/Pause", ReplyAction="http://tempuri.org/IMiscellaneousService/PauseResponse")]
        tbot_client.Miscellaneous.ResponseValue Pause();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscellaneousService/Pause", ReplyAction="http://tempuri.org/IMiscellaneousService/PauseResponse")]
        System.Threading.Tasks.Task<tbot_client.Miscellaneous.ResponseValue> PauseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscellaneousService/AddUser", ReplyAction="http://tempuri.org/IMiscellaneousService/AddUserResponse")]
        tbot_client.Miscellaneous.ResponseValue AddUser(string telegramUUID, string[] roles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscellaneousService/AddUser", ReplyAction="http://tempuri.org/IMiscellaneousService/AddUserResponse")]
        System.Threading.Tasks.Task<tbot_client.Miscellaneous.ResponseValue> AddUserAsync(string telegramUUID, string[] roles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscellaneousService/RemoveUser", ReplyAction="http://tempuri.org/IMiscellaneousService/RemoveUserResponse")]
        tbot_client.Miscellaneous.ResponseValue RemoveUser(string telegramUUID, string[] roles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscellaneousService/RemoveUser", ReplyAction="http://tempuri.org/IMiscellaneousService/RemoveUserResponse")]
        System.Threading.Tasks.Task<tbot_client.Miscellaneous.ResponseValue> RemoveUserAsync(string telegramUUID, string[] roles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscellaneousService/Test", ReplyAction="http://tempuri.org/IMiscellaneousService/TestResponse")]
        tbot_client.Miscellaneous.ResponseValue Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscellaneousService/Test", ReplyAction="http://tempuri.org/IMiscellaneousService/TestResponse")]
        System.Threading.Tasks.Task<tbot_client.Miscellaneous.ResponseValue> TestAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMiscellaneousServiceChannel : tbot_client.Miscellaneous.IMiscellaneousService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MiscellaneousServiceClient : System.ServiceModel.ClientBase<tbot_client.Miscellaneous.IMiscellaneousService>, tbot_client.Miscellaneous.IMiscellaneousService {
        
        public MiscellaneousServiceClient() {
        }
        
        public MiscellaneousServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MiscellaneousServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiscellaneousServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiscellaneousServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public tbot_client.Miscellaneous.ResponseValue AdminSay(string message) {
            return base.Channel.AdminSay(message);
        }
        
        public System.Threading.Tasks.Task<tbot_client.Miscellaneous.ResponseValue> AdminSayAsync(string message) {
            return base.Channel.AdminSayAsync(message);
        }
        
        public tbot_client.Miscellaneous.ResponseValue Pause() {
            return base.Channel.Pause();
        }
        
        public System.Threading.Tasks.Task<tbot_client.Miscellaneous.ResponseValue> PauseAsync() {
            return base.Channel.PauseAsync();
        }
        
        public tbot_client.Miscellaneous.ResponseValue AddUser(string telegramUUID, string[] roles) {
            return base.Channel.AddUser(telegramUUID, roles);
        }
        
        public System.Threading.Tasks.Task<tbot_client.Miscellaneous.ResponseValue> AddUserAsync(string telegramUUID, string[] roles) {
            return base.Channel.AddUserAsync(telegramUUID, roles);
        }
        
        public tbot_client.Miscellaneous.ResponseValue RemoveUser(string telegramUUID, string[] roles) {
            return base.Channel.RemoveUser(telegramUUID, roles);
        }
        
        public System.Threading.Tasks.Task<tbot_client.Miscellaneous.ResponseValue> RemoveUserAsync(string telegramUUID, string[] roles) {
            return base.Channel.RemoveUserAsync(telegramUUID, roles);
        }
        
        public tbot_client.Miscellaneous.ResponseValue Test() {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<tbot_client.Miscellaneous.ResponseValue> TestAsync() {
            return base.Channel.TestAsync();
        }
    }
}
