//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tbot_client.AccessPolicy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseValue", Namespace="http://schemas.datacontract.org/2004/07/kf2server_tbot_client.Utils")]
    [System.SerializableAttribute()]
    public partial class ResponseValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccessPolicy.IAccessPolicyService")]
    public interface IAccessPolicyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPolicyService/GamePasswordOn", ReplyAction="http://tempuri.org/IAccessPolicyService/GamePasswordOnResponse")]
        tbot_client.AccessPolicy.ResponseValue GamePasswordOn(string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPolicyService/GamePasswordOn", ReplyAction="http://tempuri.org/IAccessPolicyService/GamePasswordOnResponse")]
        System.Threading.Tasks.Task<tbot_client.AccessPolicy.ResponseValue> GamePasswordOnAsync(string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPolicyService/GamePasswordOff", ReplyAction="http://tempuri.org/IAccessPolicyService/GamePasswordOffResponse")]
        tbot_client.AccessPolicy.ResponseValue GamePasswordOff();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPolicyService/GamePasswordOff", ReplyAction="http://tempuri.org/IAccessPolicyService/GamePasswordOffResponse")]
        System.Threading.Tasks.Task<tbot_client.AccessPolicy.ResponseValue> GamePasswordOffAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccessPolicyServiceChannel : tbot_client.AccessPolicy.IAccessPolicyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccessPolicyServiceClient : System.ServiceModel.ClientBase<tbot_client.AccessPolicy.IAccessPolicyService>, tbot_client.AccessPolicy.IAccessPolicyService {
        
        public AccessPolicyServiceClient() {
        }
        
        public AccessPolicyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccessPolicyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessPolicyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessPolicyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public tbot_client.AccessPolicy.ResponseValue GamePasswordOn(string pwd) {
            return base.Channel.GamePasswordOn(pwd);
        }
        
        public System.Threading.Tasks.Task<tbot_client.AccessPolicy.ResponseValue> GamePasswordOnAsync(string pwd) {
            return base.Channel.GamePasswordOnAsync(pwd);
        }
        
        public tbot_client.AccessPolicy.ResponseValue GamePasswordOff() {
            return base.Channel.GamePasswordOff();
        }
        
        public System.Threading.Tasks.Task<tbot_client.AccessPolicy.ResponseValue> GamePasswordOffAsync() {
            return base.Channel.GamePasswordOffAsync();
        }
    }
}
